# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/liaochao/workspace/mysylar

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/liaochao/workspace/mysylar

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/liaochao/workspace/mysylar/CMakeFiles /home/liaochao/workspace/mysylar/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/liaochao/workspace/mysylar/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_fiber

# Build rule for target.
test_fiber: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_fiber
.PHONY : test_fiber

# fast build rule for target.
test_fiber/fast:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/build
.PHONY : test_fiber/fast

#=============================================================================
# Target rules for targets named test_util

# Build rule for target.
test_util: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_util
.PHONY : test_util

# fast build rule for target.
test_util/fast:
	$(MAKE) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/build
.PHONY : test_util/fast

#=============================================================================
# Target rules for targets named test_config

# Build rule for target.
test_config: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_config
.PHONY : test_config

# fast build rule for target.
test_config/fast:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/build
.PHONY : test_config/fast

#=============================================================================
# Target rules for targets named test_thread

# Build rule for target.
test_thread: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_thread
.PHONY : test_thread

# fast build rule for target.
test_thread/fast:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/build
.PHONY : test_thread/fast

#=============================================================================
# Target rules for targets named test

# Build rule for target.
test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test
.PHONY : test

# fast build rule for target.
test/fast:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/build
.PHONY : test/fast

#=============================================================================
# Target rules for targets named mysylar

# Build rule for target.
mysylar: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mysylar
.PHONY : mysylar

# fast build rule for target.
mysylar/fast:
	$(MAKE) -f CMakeFiles/mysylar.dir/build.make CMakeFiles/mysylar.dir/build
.PHONY : mysylar/fast

mysylar/config.o: mysylar/config.cpp.o

.PHONY : mysylar/config.o

# target to build an object file
mysylar/config.cpp.o:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/mysylar/config.cpp.o
	$(MAKE) -f CMakeFiles/mysylar.dir/build.make CMakeFiles/mysylar.dir/mysylar/config.cpp.o
.PHONY : mysylar/config.cpp.o

mysylar/config.i: mysylar/config.cpp.i

.PHONY : mysylar/config.i

# target to preprocess a source file
mysylar/config.cpp.i:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/mysylar/config.cpp.i
	$(MAKE) -f CMakeFiles/mysylar.dir/build.make CMakeFiles/mysylar.dir/mysylar/config.cpp.i
.PHONY : mysylar/config.cpp.i

mysylar/config.s: mysylar/config.cpp.s

.PHONY : mysylar/config.s

# target to generate assembly for a file
mysylar/config.cpp.s:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/mysylar/config.cpp.s
	$(MAKE) -f CMakeFiles/mysylar.dir/build.make CMakeFiles/mysylar.dir/mysylar/config.cpp.s
.PHONY : mysylar/config.cpp.s

mysylar/fiber.o: mysylar/fiber.cpp.o

.PHONY : mysylar/fiber.o

# target to build an object file
mysylar/fiber.cpp.o:
	$(MAKE) -f CMakeFiles/mysylar.dir/build.make CMakeFiles/mysylar.dir/mysylar/fiber.cpp.o
.PHONY : mysylar/fiber.cpp.o

mysylar/fiber.i: mysylar/fiber.cpp.i

.PHONY : mysylar/fiber.i

# target to preprocess a source file
mysylar/fiber.cpp.i:
	$(MAKE) -f CMakeFiles/mysylar.dir/build.make CMakeFiles/mysylar.dir/mysylar/fiber.cpp.i
.PHONY : mysylar/fiber.cpp.i

mysylar/fiber.s: mysylar/fiber.cpp.s

.PHONY : mysylar/fiber.s

# target to generate assembly for a file
mysylar/fiber.cpp.s:
	$(MAKE) -f CMakeFiles/mysylar.dir/build.make CMakeFiles/mysylar.dir/mysylar/fiber.cpp.s
.PHONY : mysylar/fiber.cpp.s

mysylar/log.o: mysylar/log.cpp.o

.PHONY : mysylar/log.o

# target to build an object file
mysylar/log.cpp.o:
	$(MAKE) -f CMakeFiles/mysylar.dir/build.make CMakeFiles/mysylar.dir/mysylar/log.cpp.o
.PHONY : mysylar/log.cpp.o

mysylar/log.i: mysylar/log.cpp.i

.PHONY : mysylar/log.i

# target to preprocess a source file
mysylar/log.cpp.i:
	$(MAKE) -f CMakeFiles/mysylar.dir/build.make CMakeFiles/mysylar.dir/mysylar/log.cpp.i
.PHONY : mysylar/log.cpp.i

mysylar/log.s: mysylar/log.cpp.s

.PHONY : mysylar/log.s

# target to generate assembly for a file
mysylar/log.cpp.s:
	$(MAKE) -f CMakeFiles/mysylar.dir/build.make CMakeFiles/mysylar.dir/mysylar/log.cpp.s
.PHONY : mysylar/log.cpp.s

mysylar/thread.o: mysylar/thread.cpp.o

.PHONY : mysylar/thread.o

# target to build an object file
mysylar/thread.cpp.o:
	$(MAKE) -f CMakeFiles/mysylar.dir/build.make CMakeFiles/mysylar.dir/mysylar/thread.cpp.o
.PHONY : mysylar/thread.cpp.o

mysylar/thread.i: mysylar/thread.cpp.i

.PHONY : mysylar/thread.i

# target to preprocess a source file
mysylar/thread.cpp.i:
	$(MAKE) -f CMakeFiles/mysylar.dir/build.make CMakeFiles/mysylar.dir/mysylar/thread.cpp.i
.PHONY : mysylar/thread.cpp.i

mysylar/thread.s: mysylar/thread.cpp.s

.PHONY : mysylar/thread.s

# target to generate assembly for a file
mysylar/thread.cpp.s:
	$(MAKE) -f CMakeFiles/mysylar.dir/build.make CMakeFiles/mysylar.dir/mysylar/thread.cpp.s
.PHONY : mysylar/thread.cpp.s

mysylar/util/util.o: mysylar/util/util.cpp.o

.PHONY : mysylar/util/util.o

# target to build an object file
mysylar/util/util.cpp.o:
	$(MAKE) -f CMakeFiles/mysylar.dir/build.make CMakeFiles/mysylar.dir/mysylar/util/util.cpp.o
.PHONY : mysylar/util/util.cpp.o

mysylar/util/util.i: mysylar/util/util.cpp.i

.PHONY : mysylar/util/util.i

# target to preprocess a source file
mysylar/util/util.cpp.i:
	$(MAKE) -f CMakeFiles/mysylar.dir/build.make CMakeFiles/mysylar.dir/mysylar/util/util.cpp.i
.PHONY : mysylar/util/util.cpp.i

mysylar/util/util.s: mysylar/util/util.cpp.s

.PHONY : mysylar/util/util.s

# target to generate assembly for a file
mysylar/util/util.cpp.s:
	$(MAKE) -f CMakeFiles/mysylar.dir/build.make CMakeFiles/mysylar.dir/mysylar/util/util.cpp.s
.PHONY : mysylar/util/util.cpp.s

test/test.o: test/test.cpp.o

.PHONY : test/test.o

# target to build an object file
test/test.cpp.o:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test/test.cpp.o
.PHONY : test/test.cpp.o

test/test.i: test/test.cpp.i

.PHONY : test/test.i

# target to preprocess a source file
test/test.cpp.i:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test/test.cpp.i
.PHONY : test/test.cpp.i

test/test.s: test/test.cpp.s

.PHONY : test/test.s

# target to generate assembly for a file
test/test.cpp.s:
	$(MAKE) -f CMakeFiles/test.dir/build.make CMakeFiles/test.dir/test/test.cpp.s
.PHONY : test/test.cpp.s

test/test_config.o: test/test_config.cpp.o

.PHONY : test/test_config.o

# target to build an object file
test/test_config.cpp.o:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/test/test_config.cpp.o
.PHONY : test/test_config.cpp.o

test/test_config.i: test/test_config.cpp.i

.PHONY : test/test_config.i

# target to preprocess a source file
test/test_config.cpp.i:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/test/test_config.cpp.i
.PHONY : test/test_config.cpp.i

test/test_config.s: test/test_config.cpp.s

.PHONY : test/test_config.s

# target to generate assembly for a file
test/test_config.cpp.s:
	$(MAKE) -f CMakeFiles/test_config.dir/build.make CMakeFiles/test_config.dir/test/test_config.cpp.s
.PHONY : test/test_config.cpp.s

test/test_fiber.o: test/test_fiber.cpp.o

.PHONY : test/test_fiber.o

# target to build an object file
test/test_fiber.cpp.o:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/test/test_fiber.cpp.o
.PHONY : test/test_fiber.cpp.o

test/test_fiber.i: test/test_fiber.cpp.i

.PHONY : test/test_fiber.i

# target to preprocess a source file
test/test_fiber.cpp.i:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/test/test_fiber.cpp.i
.PHONY : test/test_fiber.cpp.i

test/test_fiber.s: test/test_fiber.cpp.s

.PHONY : test/test_fiber.s

# target to generate assembly for a file
test/test_fiber.cpp.s:
	$(MAKE) -f CMakeFiles/test_fiber.dir/build.make CMakeFiles/test_fiber.dir/test/test_fiber.cpp.s
.PHONY : test/test_fiber.cpp.s

test/test_thread.o: test/test_thread.cpp.o

.PHONY : test/test_thread.o

# target to build an object file
test/test_thread.cpp.o:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/test/test_thread.cpp.o
.PHONY : test/test_thread.cpp.o

test/test_thread.i: test/test_thread.cpp.i

.PHONY : test/test_thread.i

# target to preprocess a source file
test/test_thread.cpp.i:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/test/test_thread.cpp.i
.PHONY : test/test_thread.cpp.i

test/test_thread.s: test/test_thread.cpp.s

.PHONY : test/test_thread.s

# target to generate assembly for a file
test/test_thread.cpp.s:
	$(MAKE) -f CMakeFiles/test_thread.dir/build.make CMakeFiles/test_thread.dir/test/test_thread.cpp.s
.PHONY : test/test_thread.cpp.s

test/test_util.o: test/test_util.cpp.o

.PHONY : test/test_util.o

# target to build an object file
test/test_util.cpp.o:
	$(MAKE) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/test/test_util.cpp.o
.PHONY : test/test_util.cpp.o

test/test_util.i: test/test_util.cpp.i

.PHONY : test/test_util.i

# target to preprocess a source file
test/test_util.cpp.i:
	$(MAKE) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/test/test_util.cpp.i
.PHONY : test/test_util.cpp.i

test/test_util.s: test/test_util.cpp.s

.PHONY : test/test_util.s

# target to generate assembly for a file
test/test_util.cpp.s:
	$(MAKE) -f CMakeFiles/test_util.dir/build.make CMakeFiles/test_util.dir/test/test_util.cpp.s
.PHONY : test/test_util.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... test_fiber"
	@echo "... rebuild_cache"
	@echo "... test_util"
	@echo "... test_config"
	@echo "... edit_cache"
	@echo "... test_thread"
	@echo "... test"
	@echo "... mysylar"
	@echo "... mysylar/config.o"
	@echo "... mysylar/config.i"
	@echo "... mysylar/config.s"
	@echo "... mysylar/fiber.o"
	@echo "... mysylar/fiber.i"
	@echo "... mysylar/fiber.s"
	@echo "... mysylar/log.o"
	@echo "... mysylar/log.i"
	@echo "... mysylar/log.s"
	@echo "... mysylar/thread.o"
	@echo "... mysylar/thread.i"
	@echo "... mysylar/thread.s"
	@echo "... mysylar/util/util.o"
	@echo "... mysylar/util/util.i"
	@echo "... mysylar/util/util.s"
	@echo "... test/test.o"
	@echo "... test/test.i"
	@echo "... test/test.s"
	@echo "... test/test_config.o"
	@echo "... test/test_config.i"
	@echo "... test/test_config.s"
	@echo "... test/test_fiber.o"
	@echo "... test/test_fiber.i"
	@echo "... test/test_fiber.s"
	@echo "... test/test_thread.o"
	@echo "... test/test_thread.i"
	@echo "... test/test_thread.s"
	@echo "... test/test_util.o"
	@echo "... test/test_util.i"
	@echo "... test/test_util.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

